Switched to the new config mechanism. Greatly simplified.

diff --git a/build/check-customs b/build/check-customs
--- a/build/check-customs
+++ b/build/check-customs
@@ -13,27 +13,13 @@ function try
 	mkdir $TDIR
 	echo "### Test $TEST: $@ ###" | tee $TDIR/log
 
-	CUST=$1
-	shift
-	SUBST=
-	APP="!!### Added by check-customs:"
-	while [ -n "$1" ] ; do
-		X=$1
-		Y=${X#!}
-		if [ "$X" != "$Y" ] ; then
-			SUBST="${S}/^$Y/s/^/# /;"
-		else
-			APP="$APP!$X"
-		fi
-		shift
-	done
-
 	(
 		cd $TDIR
-		cp -a ../../$CUST custom
-		sed "$SUBST;p;d" <../../$CUST/config.mk >custom/config.mk
-		echo $APP | tr ! '\n' >>custom/config.mk
-		if ! make -f ../../Makefile s=../.. >>log 2>&1 ; then
+		if ! ../../configure $@ CC=gcc-3.0 >>log 2>&1 ; then
+			echo "	CANNOT CONFIGURE"
+			exit 1
+		fi
+		if ! make NEWCONFIG=1 >>log 2>&1 ; then
 			echo "	FAILED"
 			exit 1
 		fi
@@ -47,13 +33,14 @@ if [ -n "$1" ] ; then
 	try "$@"
 else
 	try free									# the free version
-	try bare !CONFIG_INDEXER !CONFIG_SEARCH						# absolutely stripped version
+	try bare -CONFIG_INDEXER -CONFIG_SEARCH						# absolutely stripped version
 	try bare									# the bare version
 	try debug/matcher-test								# bare + custom stats and matchers
-	try centrum !CONFIG_GATHERER !CONFIG_GATHERD !CONFIG_SHEPHERD !CONFIG_REAPD !CONFIG_INDEXER !CONFIG_MUX !CONFIG_WATSON	# search servers
-	try centrum !CONFIG_GATHERER !CONFIG_GATHERD !CONFIG_SHEPHERD !CONFIG_REAPD !CONFIG_MUX !CONFIG_WATSON	# indexing server
-	try centrum !CONFIG_GATHERD !CONFIG_SHEPHERD !CONFIG_INDEXER !CONFIG_SEARCH !CONFIG_MUX !CONFIG_WATSON	# reapd server
-	try centrum 		 							# full Centrum config
-	try debug/custom CONFIG_SHARED=1						# debugging configuration with shared libs
-	try debug/custom								# debugging configuration
+	try centrum/cz ROLE=search							# various Centrum.cz configurations
+	try centrum/cz ROLE=indexer
+	try centrum/cz ROLE=gather
+	try centrum/cz ROLE=reap
+	try centrum/cz ROLE=all
+	try debug CONFIG_SHARED								# debugging configuration with shared libs
+	try debug									# debugging configuration
 fi
